CatCook/Controllers/ForumController.cs
using CatCook.Core.Contracts;
using CatCook.Core.Models.Comment;
using CatCook.Core.Models.Forum;
using CatCook.Core.Services;
using CatCook.Extensions;
using CatCook.Models;
using CatCook.NewFolder;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace CatCook.Controllers
{
    [Authorize]
    public class ForumController : Controller
    {
        private readonly ILogger<ForumController> _logger;
        private readonly IForumService forumService;

        public ForumController(
            ILogger<ForumController> logger,
            IForumService _forumService)
        {
            _logger = logger;
            forumService = _forumService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery]AllForumsQueryModel query)
        {
            var result = await forumService.AllForums(
                query.SearchTerm,
                query.CurrentPage,
                AllForumsQueryModel.ForumsPerPage);

            query.TotalForumsCount = result.TotalForumsCount;
            query.Forums = result.Forums;

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new ForumModel()
            {
                UserId = User.Id()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(ForumModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.DateAdded = DateTime.Now;

            int id = await forumService.Create(model);
            return RedirectToAction(nameof(All));
        }

        [RestoreModelStateFromTempData]
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            if ((await forumService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var item1 = await forumService.ForumDetailsById(id);
            var item2 = new CommentModel()
            {
                ForumId = item1.Id,
                UserId = User.Id()
            };

            var model = new Tuple<ForumDetailsModel, CommentModel>(item1, item2);
            ViewBag.UserId = User.Id();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if ((await forumService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await forumService.ForumWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var forum = await forumService.ForumDetailsById(id);

            var model = new ForumModel()
            {
                Id = forum.Id,
                Title = forum.Title,
                Text = forum.Text,
                UserId = forum.UserId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, ForumModel model)
        {
            if (id != model.Id)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await forumService.Exists(model.Id)) == false)
            {
                return View(model);
            }

            if ((await forumService.ForumWithUserId(model.Id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            await forumService.Edit(model.Id, model);

            return RedirectToAction(nameof(Details), new { id = model.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if ((await forumService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await forumService.ForumWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var forum = await forumService.ForumDetailsById(id);
            var model = new ForumDetailsModel
            {
                Id = forum.Id,
                Title = forum.Title,
                DateAdded = forum.DateAdded
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, ForumDetailsModel model)
        {
            if ((await forumService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await forumService.ForumWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            await forumService.Delete(id);

            return RedirectToAction(nameof(All));
        }
    }
}

CatCook/Controllers/RecipeController.cs
using CatCook.Core.Contracts;
using CatCook.Core.Models.Recipe;
using CatCook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;
using static CatCook.Extensions.ClaimsPrincipalExtension;

namespace CatCook.Controllers
{
    [Authorize]
    public class RecipeController : Controller
    {
        private readonly ILogger<RecipeController> _logger;
        private readonly IRecipeService recipeService;

        public RecipeController(
            ILogger<RecipeController> logger,
            IRecipeService _recipeService)
        {
            _logger = logger;
            recipeService = _recipeService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery]AllRecipesQueryModel query)
        {
            var result = await recipeService.AllRecipes(
                User.Id(), User.IsInRole("Administrator"),
                query.Category,
                query.Difficulty,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllRecipesQueryModel.RecipesPerPage);

            query.TotalRecipesCount = result.TotalRecipesCount;
            query.Categories = await recipeService.AllCategoriesNames();
            query.Difficulties = await recipeService.AllDifficultiesNames();
            query.Recipes = result.Recipes;

            return View(query);
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            if ((await recipeService.Exists(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var model = await recipeService.RecipeDetailsById(id, User.Id(), User.IsInRole("Admin"));
            ViewBag.UserId = User.Id();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new RecipeModel()
            {
                RecipeCategories = await recipeService.AllCategories(),
                RecipeDifficulties = await recipeService.AllDifficulties(),
                UserId = User.Id()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(RecipeModel model)
        {
            if ((await recipeService.CategoryExists(model.CategoryId)) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Категорията не съществува");
            }

            if ((await recipeService.DifficultyExists(model.DifficultyId)) == false)
            {
                ModelState.AddModelError(nameof(model.DifficultyId), "Тази трудност не съществува");
            }

            if (!ModelState.IsValid)
            {
                model.RecipeCategories = await recipeService.AllCategories();
                model.RecipeDifficulties = await recipeService.AllDifficulties();

                return View(model);
            }

            model.UserId = User.Id();
            int id = await recipeService.Create(model);

            return RedirectToAction(nameof(Details), new { id = id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if ((await recipeService.Exists(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await recipeService.RecipeWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var recipe = await recipeService.RecipeDetailsById(id, User.Id(), User.IsInRole("Admin"));

            var model = new RecipeModel()
            {
                Id = id,
                CategoryId = recipe.CategoryId,
                DifficultyId = recipe.DifficultyId,
                Name = recipe.Name,
                UserId = User.Id(),
                ImageUrl = recipe.ImageUrl,
                IsPrivate = recipe.IsPrivate,
                TimeForCooking = recipe.TimeForCooking,
                TimeForPreparation = recipe.TimeForPreparation,
                Description = recipe.Description,
                PortionsCount = recipe.PortionsCount,
                Rating = double.Parse(recipe.Rating)
            };

            model.RecipeCategories = await recipeService.AllCategories();
            model.RecipeDifficulties = await recipeService.AllDifficulties();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, RecipeModel model)
        {
            if (id != model.Id)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await recipeService.Exists(model.Id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                model.RecipeCategories = await recipeService.AllCategories();
                model.RecipeDifficulties = await recipeService.AllDifficulties();

                return View(model);
            }

            if ((await recipeService.RecipeWithUserId(model.Id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await recipeService.CategoryExists(model.CategoryId)) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist");
                model.RecipeCategories = await recipeService.AllCategories();
                model.RecipeDifficulties = await recipeService.AllDifficulties();

                return View(model);
            }

            if (ModelState.IsValid == false)
            {
                model.RecipeCategories = await recipeService.AllCategories();
                model.RecipeDifficulties = await recipeService.AllDifficulties();

                return View(model);
            }

            await recipeService.Edit(model.Id, model);

            return RedirectToAction(nameof(Details), new { id = model.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if ((await recipeService.Exists(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await recipeService.RecipeWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var recipe = await recipeService.RecipeDetailsById(id, User.Id(), User.IsInRole("Admin"));
            var model = new RecipeDetailsModel
            {
                Id = recipe.Id,
                Name = recipe.Name,
                DateAdded = recipe.DateAdded
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, RecipeDetailsModel model)
        {
            if ((await recipeService.Exists(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await recipeService.RecipeWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            await recipeService.Delete(id);

            return RedirectToAction(nameof(All));
        }
    }
}

CatCook/Controllers/TipController.cs
using CatCook.Core.Contracts;
using CatCook.Core.Models.Recipe;
using CatCook.Core.Models.Tip;
using CatCook.Core.Services;
using CatCook.Extensions;
using CatCook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CatCook.Controllers
{
    [Authorize]
    public class TipController : Controller
    {
        private readonly ILogger<TipController> _logger;
        private readonly ITipService tipService;

        public TipController(
            ITipService _tipService,
            ILogger<TipController> logger)
        {
            _logger = logger;
            tipService = _tipService;
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> All([FromQuery]AllTipsQueryModel query)
        {
            var result = await tipService.AllTips(
                query.SearchTerm,
                query.CurrentPage,
                AllTipsQueryModel.TipsPerPage);

            query.TotalTipsCount = result.TotalTipsCount;
            query.Tips = result.Tips;

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new TipModel()
            {
                UserId = User.Id()
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(TipModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            model.UserId = User.Id();
            model.DateAdded = DateTime.Now;

            int id = await tipService.Create(model);
            return RedirectToAction(nameof(Details), new { id = id });
        }

        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            if ((await tipService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var model = await tipService.TipDetailsById(id);
            ViewBag.UserId = User.Id();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            if ((await tipService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await tipService.TipWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var tip = await tipService.TipDetailsById(id);

            var model = new TipModel()
            {
                Id = id,
                Title = tip.Title,
                Description = tip.Description,
                UserId = tip.UserId
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, TipModel model)
        {
            if (id != model.Id)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await tipService.Exists(model.Id)) == false)
            {
                return View(model);
            }

            if ((await tipService.TipWithUserId(model.Id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if (ModelState.IsValid == false)
            {
                return View(model);
            }

            await tipService.Edit(model.Id, model);

            return RedirectToAction(nameof(Details), new { id = model.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if ((await tipService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await tipService.TipWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            var tip = await tipService.TipDetailsById(id);
            var model = new TipDetailsModel
            {
                Id = tip.Id,
                Title = tip.Title,
                DateAdded = tip.DateAdded
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id, TipDetailsModel model)
        {
            if ((await tipService.Exists(id)) == false)
            {
                return RedirectToAction(nameof(All));
            }

            if ((await tipService.TipWithUserId(id, User.Id(), User.IsInRole("Admin"))) == false)
            {
                return RedirectToAction(nameof(All));
            }

            await tipService.Delete(id);

            return RedirectToAction(nameof(All));
        }
    }
}

CatCook/Areas/Admin/Views/Admin/AllAccounts.cshtml
@model AllAccountsQueryModel
@{
    ViewBag.Title = "Всички Акаунти";
}

<div class="card-deck row">
    <h1 class="text-center" style="margin-top: 10rem ; margin-bottom: 1rem;">@ViewBag.Title</h1>
    <form method="get">
        <div class="row">

            <div class="form-group col-md-3">
                <label asp-for="SearchTerm">Потърси</label>
                <input asp-for="SearchTerm" class="form-control" placeholder="...">
            </div>

            <div class="col-md-3">
                <div class="form-group mt-4 p-2">
                    <input type="submit" value="Search" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>

    @{
        var previousPage = Model.CurrentPage - 1;
        if (previousPage < 1)
        {
            previousPage = 1;
        }

        var maxPage = Math.Ceiling((double)Model.TotalAccountsCount /
        AllAccountsQueryModel.AccountsPerPage);
    }

    <div class="row mb-5">
        <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
            <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
               asp-area="Admin"
               asp-controller="Admin"
               asp-action="AllAccounts"
               asp-route-currentPage="@previousPage"
               asp-route-searchTerm="@Model.SearchTerm"><<</a>
        </div>

        @{
            var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
            !Model.Accounts.Any();
        }

        <div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
            <a class="btn btn-primary
           @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
               asp-area="Admin"
               asp-controller="Admin"
               asp-action="AllAccounts"
               asp-route-currentPage="@(Model.CurrentPage + 1)"
               asp-route-searchTerm="@Model.SearchTerm">>></a>
        </div>
    </div>
    @if (!Model.Accounts.Any())
    {
        <h2 class="text-center">Няма акаунти по тази критерия!</h2>
    }
    @foreach (var account in Model.Accounts)
    {
        @if(!(User.Id() == account.Id))
        {
            <div class="card col-12" style="width: 100%; margin-bottom: 3rem; border: #DE4D01 1px solid">
                <div class="card-body">
                    @if (account.AvatarImgUrl != null)
                    {
                        <img class="p-2 mt-5" style="object-fit: cover; width: 150px; height: 150px;" src="@account.AvatarImgUrl" alt="Profile Photo" />
                    }
                    else
                    {
                        <img class="p-2 mt-5" style="object-fit: cover; width: 150px; height: 150px;" src="~/img/no-profile-picture-icon.png" alt="Profile Photo" />
                    }
                    <h3 class="card-title">
                        <b>@@@account.ProfileName</b>
                    </h3>
                    <p class="card-text">Име: @account.FirstName @account.LastName<br />Имейл: <b>@@@account.Email</b><br />Град: <b>@account.City</b></p>
                    <p class="card-text">Статус: @account.Status</p>
                    <a class="nav-link" style="font-size=14px; font-weight: bold;" asp-area="Admin" asp-controller="Admin" asp-action="DeleteAccount" asp-route-id="@account.Id"><button type="button" class="btn btn-primary">Изтрий</button></a>
                </div>
            </div>
        }
    }
</div>

CatCook/Areas/Admin/Views/Admin/DeleteAccount.cshtml
@model AccountDetailsModel
@{
    ViewBag.Title = "Изтрий Акаунт";
}
<div class="row align-content-center">
    <h2 class="text-center" style="margin-top: 10rem;  margin-bottom: 2rem;">@ViewBag.Title</h2>
    <hr />

    <form asp-action="DeleteAccount">
        <div class="card" style="width: 18rem; margin: 0 auto;">
            <div class="card-body">
                <p class="card-text">Сигурни ли сте, че искате да изтриете акаунта <b>@@@Model.ProfileName</b> с имейл <b>@Model.Email</b>?</p>
                <div class="form-group">
                    <input type="submit" value="Изтрий" class="btn btn-danger" />
                    <a class="btn btn-secondary" asp-area="Admin" asp-controller="Admin" asp-action="AllAccounts" asp-route-id="@Model.Id">Отказ</a>
                </div>
            </div>
        </div>

    </form>
</div>

CatCook/Areas/Admin/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Начална Страница";
}

<div class="mt-4 p-5 text-center">
    <h2 style="margin-top:10rem;" class="display-4">Здравейте, Админ!</h2>
    <p class="lead mb-1 mt-3">
        Това е административната ви зона - можете да <b>редактирате</b>, <b>четете</b> и
        <b>изтривате </b> рецепти, съвети, форуми, коментари.
    </p>
    <p class="lead mt-1">
        Можете също и <b>всички потребители</b> да бъдат <b>преглеждани и изтрити</b> в системата.
    </p>
    <hr class="my-4">
    <a asp-area="" asp-controller="Recipe" asp-action="All"
       class="btn btn-primary btn-lg">Всички рецепти</a>
    <span>  |   </span>
    <a asp-area="" asp-controller="Tip" asp-action="All"
       class="btn btn-primary btn-lg">Всички съвети</a>
    <span>  |   </span>
    <a asp-area="" asp-controller="Forum" asp-action="All"
       class="btn btn-primary btn-lg">Всички форуми</a>
    <span>  |   </span>
    <a asp-area="Admin" asp-controller="Admin" asp-action="AllAccounts"
       class="btn btn-primary btn-lg">Всички акаунти</a>
</div>